development:
  adapter:  postgresql
  host:     localhost
  database: portforio_development
  encoding: unicode
  pool:     5
  username:
  password:

test:
  adapter:  postgresql
  host:     localhost
  database: portforio_test
  encoding: unicode
  pool:     5
  username:
  password:

production:
  database: portforio_production
